### ISSUE TITLE
Game rendering speed is slow

### ISSUE THREAD

**Issue by StoicEeyore** [chenxing61/Emperors-and-Deities#7]
I was playing this mod a couple of months ago, didn't seem as slow, especially during the start of the game. Mobile version, 206 turns in a large map, plot armor, all competing civs active. Takes 30 seconds to put something in the build queue, longer in the capital or new social policy. I ran it until it crashed, so I got you the error report.

**Platform:** Android
**Version:** 4.16.9 (Build 1,125)
**Rulesets:** [LesserSpaceNations, CivBE in Alpha Frontier, Nations of the World, Civ V - Vanilla, Deciv 2, DeCiv Redux, Steampunk Nations for Deciv, Brave New World Updated, Better Barbarian Rewards, Alpha Frontier, Outlaws of the Wastes, Abundant Natural Wonders, Future Expansion Continued, Warfare Expanded Lite, Civ V - Gods & Kings, Emperors and Deities, Dreams of Combustion Ambience Music, The Great Unciv Rework, DeCiv in Alpha Frontier, Leader Mission 2 Rising Power]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: SM-A125U
API Level: 31
System Memory: 2735 MB
    Available (used by Kernel): 417 MB
    System Low Memory state: false
    Java heap limit: 512 MB
    Java heap free: 0 MB

--------------------------------

**Message:**
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1111)
	at java.util.ArrayList$Itr.next(ArrayList.java:1064)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:311)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:115)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:307)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at com.unciv.logic.civilization.CivConstructions.addFreeBuildings(CivConstructions.kt:161)
	at com.unciv.logic.civilization.CivConstructions.tryAddFreeBuildings(CivConstructions.kt:72)
	at com.unciv.logic.city.CityConstructions.addBuilding(CityConstructions.kt:588)
	at com.unciv.logic.city.CityConstructions.addBuilding$default(CityConstructions.kt:547)
	at com.unciv.models.ruleset.Building.construct(Building.kt:473)
	at com.unciv.logic.city.CityConstructions.completeConstruction(CityConstructions.kt:457)
	at com.unciv.logic.civilization.CivConstructions.addFreeBuildings(CivConstructions.kt:166)
	at com.unciv.logic.civilization.CivConstructions.tryAddFreeBuildings(CivConstructions.kt:72)
	at com.unciv.logic.city.CityConstructions.addBuilding(CityConstructions.kt:588)
	at com.unciv.logic.city.CityConstructions.addBuilding$default(CityConstructions.kt:547)
	at com.unciv.models.ruleset.Building.construct(Building.kt:473)
	at com.unciv.logic.city.CityConstructions.completeConstruction(CityConstructions.kt:457)
	at com.unciv.models.ruleset.unique.UniqueTriggerActivation$getTriggerFunction$41.invoke(UniqueTriggerActivation.kt:926)
	at com.unciv.models.ruleset.unique.UniqueTriggerActivation$getTriggerFunction$41.invoke(UniqueTriggerActivation.kt:921)
	at com.unciv.models.ruleset.unique.UniqueTriggerActivation.triggerUnique(UniqueTriggerActivation.kt:76)
	at com.unciv.models.ruleset.unique.UniqueTriggerActivation.triggerUnique$default(UniqueTriggerActivation.kt:66)
	at com.unciv.models.ruleset.unique.UniqueTriggerActivation.triggerUnique(UniqueTriggerActivation.kt:52)
	at com.unciv.models.ruleset.unique.UniqueTriggerActivation.triggerUnique$default(UniqueTriggerActivation.kt:46)
	at com.unciv.logic.city.CityConstructions.triggerNewBuildingUniques(CityConstructions.kt:597)
	at com.unciv.logic.city.CityConstructions.addBuilding(CityConstructions.kt:566)
	at com.unciv.logic.city.CityConstructions.addBuilding$default(CityConstructions.kt:547)
	at com.unciv.logic.civilization.Civilization.moveCapitalTo(Civilization.kt:998)
	at com.unciv.logic.civilization.Civilization.moveCapitalToNextLargest(Civilization.kt:1040)
	at com.unciv.logic.city.managers.CityConquestFunctions.moveToCiv(CityConquestFunctions.kt:263)
	at com.unciv.logic.city.City.moveToCiv(City.kt:430)
	at com.unciv.logic.city.managers.CityConquestFunctions.conquerCity(CityConquestFunctions.kt:103)
	at com.unciv.logic.city.managers.CityConquestFunctions.puppetCity(CityConquestFunctions.kt:133)
	at com.unciv.logic.city.City.puppetCity(City.kt:423)
	at com.unciv.ui.screens.worldscreen.AlertPopup$addCityConquered$2.invoke(AlertPopup.kt:201)
	at com.unciv.ui.screens.worldscreen.AlertPopup$addCityConquered$2.invoke(AlertPopup.kt:200)
	at com.unciv.ui.screens.worldscreen.AlertPopup$addAnnexOption$1$1.invoke(AlertPopup.kt:495)
	at com.unciv.ui.screens.worldscreen.AlertPopup$addAnnexOption$1$1.invoke(AlertPopup.kt:494)
	at com.unciv.ui.components.input.ActivationActionMap.activate(ActivationActionMap.kt:57)
	at com.unciv.ui.components.input.ActorAttachments.activate(ActorAttachments.kt:42)
	at com.unciv.ui.components.input.ActivationExtensionsKt.activate(ActivationExtensions.kt:17)
	at com.unciv.ui.components.input.ActivationListener.tap(ActivationListener.kt:15)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.tap(ActorGestureListener.java:52)
	at com.badlogic.gdx.input.GestureDetector.touchUp(GestureDetector.java:206)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener.handle(ActorGestureListener.java:125)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:354)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:449)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:499)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1593)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1287)

```
**Save Mods:**
```
[Emperors and Deities, Abundant Natural Wonders, Better Barbarian Rewards]
```
**Permanent audiovisual Mods**:
```
[Dreams of Combustion Ambience Music]
```

**Comment by StoicEeyore** [comment]
I just got the mod to crash again, turns out the trigger is capturing Europa's capital. Happened around turn 84 this time, medium map, still runs really slow.

**Platform:** Android
**Version:** 4.16.9 (Build 1,125)
**Rulesets:** [LesserSpaceNations, CivBE in Alpha Frontier, Nations of the World, Civ V - Vanilla, Deciv 2, DeCiv Redux, Steampunk Nations for Deciv, Brave New World Updated, Better Barbarian Rewards, Alpha Frontier, Outlaws of the Wastes, Abundant Natural Wonders, Future Expansion Continued, Warfare Expanded Lite, Civ V - Gods & Kings, Emperors and Deities, Dreams of Combustion Ambience Music, The Great Unciv Rework, DeCiv in Alpha Frontier, Leader Mission 2 Rising Power]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: SM-A125U
API Level: 31
System Memory: 2735 MB
    Available (used by Kernel): 420 MB
    System Low Memory state: false
    Java heap limit: 512 MB
    Java heap free: 2 MB

--------------------------------


**Message:**
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1111)
	at java.util.ArrayList$Itr.next(ArrayList.java:1064)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:311)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:115)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:307)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at com.unciv.logic.civilization.CivConstructions.addFreeBuildings(CivConstructions.kt:161)
	at com.unciv.logic.civilization.CivConstructions.tryAddFreeBuildings(CivConstructions.kt:72)
	at com.unciv.logic.city.CityConstructions.addBuilding(CityConstructions.kt:588)
	at com.unciv.logic.city.CityConstructions.addBuilding$default(CityConstructions.kt:547)
	at com.unciv.models.ruleset.Building.construct(Building.kt:473)
	at com.unciv.logic.city.CityConstructions.completeConstruction(CityConstructions.kt:457)
	at com.unciv.logic.civilization.CivConstructions.addFreeBuildings(CivConstructions.kt:166)
	at com.unciv.logic.civilization.CivConstructions.tryAddFreeBuildings(CivConstructions.kt:72)
	at com.unciv.logic.city.CityConstructions.addBuilding(CityConstructions.kt:588)
	at com.unciv.logic.city.CityConstructions.addBuilding$default(CityConstructions.kt:547)
	at com.unciv.models.ruleset.Building.construct(Building.kt:473)
	at com.unciv.logic.city.CityConstructions.completeConstruction(CityConstructions.kt:457)
	at com.unciv.logic.civilization.CivConstructions.addFreeBuildings(CivConstructions.kt:166)
	at com.unciv.logic.civilization.CivConstructions.tryAddFreeBuildings(CivConstructions.kt:72)
	at com.unciv.logic.city.CityConstructions.addBuilding(CityConstructions.kt:588)
	at com.unciv.logic.city.CityConstructions.addBuilding$default(CityConstructions.kt:547)
	at com.unciv.models.ruleset.Building.construct(Building.kt:473)
	at com.unciv.logic.city.CityConstructions.completeConstruction(CityConstructions.kt:457)
	at com.unciv.models.ruleset.unique.UniqueTriggerActivation$getTriggerFunction$41.invoke(UniqueTriggerActivation.kt:926)
	at com.unciv.models.ruleset.unique.UniqueTriggerActivation$getTriggerFunction$41.invoke(UniqueTriggerActivation.kt:921)
	at com.unciv.models.ruleset.unique.UniqueTriggerActivation.triggerUnique(UniqueTriggerActivation.kt:76)
	at com.unciv.models.ruleset.unique.UniqueTriggerActivation.triggerUnique$default(UniqueTriggerActivation.kt:66)
	at com.unciv.models.ruleset.unique.UniqueTriggerActivation.triggerUnique(UniqueTriggerActivation.kt:52)
	at com.unciv.models.ruleset.unique.UniqueTriggerActivation.triggerUnique$default(UniqueTriggerActivation.kt:46)
	at com.unciv.logic.city.CityConstructions.triggerNewBuildingUniques(CityConstructions.kt:597)
	at com.unciv.logic.city.CityConstructions.addBuilding(CityConstructions.kt:566)
	at com.unciv.logic.city.CityConstructions.addBuilding$default(CityConstructions.kt:547)
	at com.unciv.logic.civilization.Civilization.moveCapitalTo(Civilization.kt:998)
	at com.unciv.logic.civilization.Civilization.moveCapitalToNextLargest(Civilization.kt:1040)
	at com.unciv.logic.city.managers.CityConquestFunctions.moveToCiv(CityConquestFunctions.kt:263)
	at com.unciv.logic.city.City.moveToCiv(City.kt:430)
	at com.unciv.logic.city.managers.CityConquestFunctions.conquerCity(CityConquestFunctions.kt:103)
	at com.unciv.logic.city.managers.CityConquestFunctions.puppetCity(CityConquestFunctions.kt:133)
	at com.unciv.logic.city.City.puppetCity(City.kt:423)
	at com.unciv.ui.screens.worldscreen.AlertPopup$addCityConquered$2.invoke(AlertPopup.kt:201)
	at com.unciv.ui.screens.worldscreen.AlertPopup$addCityConquered$2.invoke(AlertPopup.kt:200)
	at com.unciv.ui.screens.worldscreen.AlertPopup$addAnnexOption$1$1.invoke(AlertPopup.kt:495)
	at com.unciv.ui.screens.worldscreen.AlertPopup$addAnnexOption$1$1.invoke(AlertPopup.kt:494)
	at com.unciv.ui.components.input.ActivationActionMap.activate(ActivationActionMap.kt:57)
	at com.unciv.ui.components.input.ActorAttachments.activate(ActorAttachments.kt:42)
	at com.unciv.ui.components.input.ActivationExtensionsKt.activate(ActivationExtensions.kt:17)
	at com.unciv.ui.components.input.ActivationListener.tap(ActivationListener.kt:15)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.tap(ActorGestureListener.java:52)
	at com.badlogic.gdx.input.GestureDetector.touchUp(GestureDetector.java:206)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener.handle(ActorGestureListener.java:125)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:354)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:449)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:499)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1593)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1287)

```
**Save Mods:**
```
[Emperors and Deities, Abundant Natural Wonders, Better Barbarian Rewards]
```
**Permanent audiovisual Mods**:
```
[Dreams of Combustion Ambience Music]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

**Comment by chenxing61** [comment]
The crashing has been fixed via new mod update.
As for slow games:
I dont know how to fix it yet, set the map size smaller for now?

**Comment by chenxing61** [comment]
This bug may get patched in newer version, if it doesnt, I will continue with debugging

**Comment by StoicEeyore** [comment]
I'm still playing with the mod, trying to figure out what slows it down so much, but not much luck yet. I did update the mod on my phone, still getting crashes when conquering capitals. North Africa vs Europa, South Asia vs West-Central Asia and vice-versa. Do you want crash reports here, or a new thread?

**Comment by StoicEeyore** [comment]
Okay, that makes it easier, haha. Hit another crash with North Africa vs West Central Asia.

Was running with no policies at all, only 3 cities, still bogs down fast on a small map. I'll start tiny maps, 1 civ, see what happens.
